"""Export imitation_v7 weights to portable formats for C++ embedding.

Produces two artifacts:

* ``v7_weights.json`` -- human-readable dump of every tensor with
  its shape and float values, plus a header block with model
  hyperparameters. Useful for debugging + language-agnostic
  consumption.

* ``v7_weights.h`` -- C++ header intended to drop into the JIT
  source tree. Emits every tensor as ``static constexpr float``
  arrays. Shape/naming matches the PyTorch state_dict; consumers
  can index the arrays as raw 1D floats and reinterpret.

Design notes for JIT embedding (see docs/embed_v7.md for details):
* All dimensions are compile-time constants baked into the header,
  matching the JIT's C++-subset restrictions (no dynamic sizes).
* No STL types; ``const float[]`` is what the JIT can consume with
  its arena allocator.
* Follows the same pattern as ``CSE_HeuristicParameterized``'s
  ``s_defaultParameters`` -- baked-in table of floats.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from typing import Dict

import numpy as np
import torch


HEADER_TOP = """// Auto-generated by scripts/export_v7_weights.py.  Do not edit by hand.
//
// Weights for the imitation-learning CSE heuristic (v7), a
// per-candidate binary classifier trained on 23,578 MCMC-labeled
// optimal-CSE-subset examples across four MCH sources.
//
// Model architecture (see docs/embed_v7.md for the full spec):
//   * candidate_embed : Linear(FEATURES_PER_CANDIDATE -> EMBED_DIM)
//   * one transformer-encoder layer (pre-norm), num_heads=4,
//     FFN_HIDDEN=EMBED_DIM*2, activation=ReLU
//   * candidate_scorer : Linear(EMBED_DIM -> 1) on post-attention
//     candidate embeddings
//   * stop_scorer      : Linear(METHOD_FEATURES -> 1) on raw
//     (normalized) method features
//
// Inference emits (MAX_CSE + 1) logits: first MAX_CSE are per-
// candidate scores, last is the stop score. Apply sigmoid, then
// select candidates with prob > threshold (v7 best: 0.3).
//
// Total parameters: 36,494 floats = ~146KB in .rdata.

#pragma once

"""


def _emit_array(name: str, tensor: torch.Tensor, out) -> None:
    """Write a single tensor as a flat const float array."""
    arr = tensor.detach().cpu().numpy().astype(np.float32).ravel()
    out.write(f"// {name}: shape {list(tensor.shape)}\n")
    out.write(f"inline constexpr float {name}[{arr.size}] = {{\n    ")
    for i, v in enumerate(arr):
        # 9 significant digits round-trips float32 exactly.
        out.write(f"{v:.9g}f, ")
        if (i + 1) % 8 == 0:
            out.write("\n    ")
    out.write("\n};\n\n")


def _sanitize(k: str) -> str:
    """State-dict key -> valid C identifier."""
    return "k_" + k.replace(".", "_")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--checkpoint", required=True,
                    help="Path to best_val.pt")
    ap.add_argument("--config", required=True,
                    help="Path to config.json")
    ap.add_argument("--out-dir", required=True)
    args = ap.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)

    with open(args.config, encoding="utf-8") as f:
        cfg = json.load(f)

    sd: Dict[str, torch.Tensor] = torch.load(args.checkpoint, map_location="cpu")

    # ---- JSON dump ----
    json_out = {"config": cfg, "tensors": {}}
    for k, v in sd.items():
        arr = v.detach().cpu().numpy().astype(np.float32)
        json_out["tensors"][k] = {
            "shape": list(arr.shape),
            "values": arr.ravel().tolist(),
        }
    json_path = os.path.join(args.out_dir, "v7_weights.json")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(json_out, f)
    print(f"wrote {json_path} ({os.path.getsize(json_path)/1024:.0f}KB)")

    # ---- C++ header ----
    header_path = os.path.join(args.out_dir, "v7_weights.h")
    with open(header_path, "w", encoding="utf-8") as f:
        f.write(HEADER_TOP)
        f.write("namespace CseImitationV7 {\n\n")
        # Compile-time dims
        f.write(f"inline constexpr int MAX_CSE                = {cfg['MAX_CSE']};\n")
        f.write(f"inline constexpr int FEATURES_PER_CANDIDATE = {cfg['FEATURES_PER_CANDIDATE']};\n")
        f.write(f"inline constexpr int METHOD_FEATURES        = {cfg['METHOD_LEVEL_FEATURES']};\n")
        f.write(f"inline constexpr int EMBED_DIM              = {cfg['embed_dim']};\n")
        f.write(f"inline constexpr int NUM_HEADS              = {cfg['num_heads']};\n")
        f.write(f"inline constexpr int HEAD_DIM               = {cfg['embed_dim'] // cfg['num_heads']};\n")
        f.write(f"inline constexpr int FFN_HIDDEN             = {cfg['embed_dim'] * 2};\n")
        f.write(f"inline constexpr int NUM_ATTN_LAYERS        = {cfg['num_attn_layers']};\n")
        f.write("\n")

        # Emit each tensor. Order matters only for readability.
        for k, v in sd.items():
            _emit_array(_sanitize(k), v, f)

        f.write("} // namespace CseImitationV7\n")
    print(f"wrote {header_path} ({os.path.getsize(header_path)/1024:.0f}KB)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
